Feat: MannerTemp
wafflestudio19-5/team8-iOS pull request #48
Opened 2022-01-23 19:31 UTC by chaemin2001

프로필 화면과 이어지는 매너 평가하기 창 UI를 만들었습니다. 데이터 연결 및 매너 선택은 아직 구현하지 못했습니다.

2022-01-24 04:31 UTC, VioletXF requested changes
UI가 보이지 않는데 확인 후 수정 부탁드립니다.

2022-01-24 08:40 UTC, chaemin2001 commented
지금 현재 Article의 like 수가 nil로 설정되어 있어 메인 화면에도 오류가 뜨는 것 같습니다. 디폴트 0으로 설정될 수 있도록 백엔드와 연결한 후에 해결 가능하지 않을까 생각합니다.

2022-01-24 09:30 UTC, VioletXF commented
아니요, like가 nil이면 0으로 표시되도록 이미 조치하여 메인 화면에는 문제가 없습니다. 지금 문제가 있는 것은 ArticleViewController입니다.
아래와 같이 제목과 내용이 사진과 겹쳐 있고, 프로필 뷰도 표시되지 않는 상황입니다.

로그에 따르면 Constraint가 잘못 설정되어있는 것 같은데, 참고하시고 수정 부탁드립니다.
```
2022-01-24 18:29:36.428988+0900 WaffleMarket[59292:4550705] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002f98280 UIImageView:0x7fadc436b080.top == _UIScrollViewLayoutGuide:0x6000035790a0'UIScrollView-contentLayoutGuide'.top   (active)>",
    "<NSLayoutConstraint:0x600002f98230 UIImageView:0x7fadc436b080.bottom == _UIScrollViewLayoutGuide:0x6000035790a0'UIScrollView-contentLayoutGuide'.top + 300   (active)>",
    "<NSLayoutConstraint:0x600002f98500 V:[UIImageView:0x7fadc436b080]-(0)-[UIView:0x7fadc432f700]   (active)>",
    "<NSLayoutConstraint:0x600002f985a0 UIView:0x7fadc432f700.bottom == UIImageView:0x7fadc436b080.top + 70   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002f98500 V:[UIImageView:0x7fadc436b080]-(0)-[UIView:0x7fadc432f700]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-01-24 18:29:36.431546+0900 WaffleMarket[59292:4550705] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002f48730 H:[UIImageView:0x7fadc4306e30]-(10)-[UIButton:0x7fadc436db90]   (active)>",
    "<NSLayoutConstraint:0x600002f52030 UIButton:0x7fadc436db90.centerX == UIImageView:0x7fadc4306e30.centerX   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002f48730 H:[UIImageView:0x7fadc4306e30]-(10)-[UIButton:0x7fadc436db90]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-01-24 18:29:36.467279+0900 WaffleMarket[59292:4550705] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600002f90550 h=--& v=--& UIButton:0x7fadc436db90.minX == 0   (active, names: '|':UIView:0x7fadc432f700 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x600002f905a0 h=--& v=--& UIButton:0x7fadc436db90.width == 0   (active)>",
    "<NSLayoutConstraint:0x600002f6eee0 UIImageView:0x7fadc436b080.leading == UILayoutGuide:0x600003516ae0'UIViewSafeAreaLayoutGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x600002f982d0 UIImageView:0x7fadc436b080.trailing == UILayoutGuide:0x600003516ae0'UIViewSafeAreaLayoutGuide'.trailing   (active)>",
    "<NSLayoutConstraint:0x600002f98460 UIView:0x7fadc432f700.leading == UIImageView:0x7fadc436b080.leading   (active)>",
    "<NSLayoutConstraint:0x600002f98550 UIView:0x7fadc432f700.trailing == UIImageView:0x7fadc436b080.trailing   (active)>",
    "<NSLayoutConstraint:0x600002f4a990 UIImageView:0x7fadc4306e30.centerX == UIView:0x7fadc432f700.centerX   (active)>",
    "<NSLayoutConstraint:0x600002f52030 UIButton:0x7fadc436db90.centerX == UIImageView:0x7fadc4306e30.centerX   (active)>",
    "<NSLayoutConstraint:0x600002f907d0 'UIView-Encapsulated-Layout-Width' UIView:0x7fadc420b690.width == 390   (active)>",
    "<NSLayoutConstraint:0x600002f71e50 'UIViewSafeAreaLayoutGuide-left' H:|-(0)-[UILayoutGuide:0x600003516ae0'UIViewSafeAreaLayoutGuide'](LTR)   (active, names: '|':UIView:0x7fadc420b690 )>",
    "<NSLayoutConstraint:0x600002f71810 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x600003516ae0'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: '|':UIView:0x7fadc420b690 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002f52030 UIButton:0x7fadc436db90.centerX == UIImageView:0x7fadc4306e30.centerX   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-01-24 18:29:36.469133+0900 WaffleMarket[59292:4550705] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600002f90690 h=--& v=--& UILabel:0x7fadc436de50.minX == 0   (active, names: '|':UIView:0x7fadc432f700 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x600002f906e0 h=--& v=--& UILabel:0x7fadc436de50.width == 0   (active)>",
    "<NSLayoutConstraint:0x600002f6eee0 UIImageView:0x7fadc436b080.leading == UILayoutGuide:0x600003516ae0'UIViewSafeAreaLayoutGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x600002f982d0 UIImageView:0x7fadc436b080.trailing == UILayoutGuide:0x600003516ae0'UIViewSafeAreaLayoutGuide'.trailing   (active)>",
    "<NSLayoutConstraint:0x600002f98460 UIView:0x7fadc432f700.leading == UIImageView:0x7fadc436b080.leading   (active)>",
    "<NSLayoutConstraint:0x600002f98550 UIView:0x7fadc432f700.trailing == UIImageView:0x7fadc436b080.trailing   (active)>",
    "<NSLayoutConstraint:0x600002f52080 UILabel:0x7fadc436de50.trailing == UIView:0x7fadc432f700.trailing + 20   (active)>",
    "<NSLayoutConstraint:0x600002f907d0 'UIView-Encapsulated-Layout-Width' UIView:0x7fadc420b690.width == 390   (active)>",
    "<NSLayoutConstraint:0x600002f71e50 'UIViewSafeAreaLayoutGuide-left' H:|-(0)-[UILayoutGuide:0x600003516ae0'UIViewSafeAreaLayoutGuide'](LTR)   (active, names: '|':UIView:0x7fadc420b690 )>",
    "<NSLayoutConstraint:0x600002f71810 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x600003516ae0'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: '|':UIView:0x7fadc420b690 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002f52080 UILabel:0x7fadc436de50.trailing == UIView:0x7fadc432f700.trailing + 20   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```
![image](https://user-images.githubusercontent.com/27609690/150756543-0aa80833-cfce-4206-b069-79b1132fb570.png)

2022-01-24 12:12 UTC, chaemin2001 commented
문제가 되는 것 같은 부분을 수정해 두었습니다! 제 시뮬레이터에는 메인 화면이 보이지 않고 게시물 등록에 오류가 나는 것 같은데 이유가 있을까요
<img width="339" alt="스크린샷 2022-01-24 오후 9 12 02" src="https://user-images.githubusercontent.com/74291744/150780894-eb58d290-6d08-48ff-9669-799bb863d85c.png">

2022-01-24 14:23 UTC, VioletXF commented
로그에 나와있는 바와 같이 인증이 만료돼서 그렇습니다. 현재 백엔드 설정상 토큰이 하루만에 만료되므로, 저 에러가 발생하면 로그아웃 후 다시 로그인하시면 됩니다.

2022-01-24 16:07 UTC, chaemin2001 commented
앗 감사합니다 확인해서 조금 어색한 부분도 수정해두었습니다

2022-01-24 16:59 UTC, VioletXF commented
여전히 뷰가 보이지 않아 일단 제가 디자인적인 측면은 고려하지 않고 ArticleView의 모든 Constraint 오류를 고치는 데에만 집중하여 뷰가 보이게끔 만들었는데, 배치는 적절히 수정해주시기 바랍니다.

그리고, UI에 이모티콘을 사용하지 않도록 주의해주세요. 시스템 폰트에 따라 달라 보이므로 일관성이 없습니다. 대신 SF Symbols에서 적절한 이미지를 찾아 ImageView에 넣는 것이 좋습니다.

2022-01-25 18:30 UTC, chaemin2001 commented
@VioletXF 표시되지 않는 UI와 버튼 확인해서 수정했습니다. 커밋해주신 부분도 확인했어요! 감사합니다.

2022-01-26 08:22 UTC, VioletXF commented
@chaemin2001 complimentLabel이 두 줄까지 표시하도록 변경하였습니다. 수고하셨습니다.

2022-01-26 08:22 UTC, VioletXF approved these changes

2022-01-26 10:52 UTC, merged